### Phép toán trên mảng(Array Math)

In [1]:
# aivietnam.ai
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x \n', x)
print('data y \n', y)

# Tổng của 2 mảng
print('method 1 \n', x + y)
print('method 2 \n', np.add(x, y))

data x 
 [1 2 3 4]
data y 
 [5 6 7 8]
method 1 
 [ 6  8 10 12]
method 2 
 [ 6  8 10 12]


In [2]:
# aivietnam.ai
import numpy as np

x = np.array([5,6,7,8])
y = np.array([1,2,3,4])

print('data x \n', x)
print('data y \n', y)

# Hiệu 2 mảng
print('method 1 \n', x - y)
print('method 2 \n', np.subtract(x, y))

data x 
 [5 6 7 8]
data y 
 [1 2 3 4]
method 1 
 [4 4 4 4]
method 2 
 [4 4 4 4]


In [3]:
# aivietnam.ai
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x \n', x)
print('data y \n', y)

# Tích các phần tử tương ứng giữa x và y
print('method 1 \n', x*y)
print('method 2 \n', np.multiply(x, y))

data x 
 [1 2 3 4]
data y 
 [5 6 7 8]
method 1 
 [ 5 12 21 32]
method 2 
 [ 5 12 21 32]


In [4]:
# aivietnam.ai
import numpy as np

x = np.array([5,6,7,8])
y = np.array([1,2,3,4])

print('data x \n', x)
print('data y \n', y)

# Phép chia các từng phần tương ứng x cho y
print('method 1 \n', x / y)
print('method 2 \n', x // y)
print('method 3 \n', np.divide(x, y))

data x 
 [5 6 7 8]
data y 
 [1 2 3 4]
method 1 
 [5.         3.         2.33333333 2.        ]
method 2 
 [5 3 2 2]
method 3 
 [5.         3.         2.33333333 2.        ]


In [5]:
# aivietnam.ai
import numpy as np

data = np.array([1,2,3,4])

print('data \n', data)

# Căn bậc 2 từng phần tử trong data
print('sqrt \n', np.sqrt(data))

data 
 [1 2 3 4]
sqrt 
 [1.         1.41421356 1.73205081 2.        ]


In [6]:
# aivietnam.ai
import numpy as np

v = np.array([1, 2])
w = np.array([2, 3])

# Tính inner product giữa v và w
print('method 1 \n', v.T.dot(w))
print('method 2 \n', np.dot(v, w))

method 1 
 8
method 2 
 8


In [7]:
# aivietnam.ai
import numpy as np

v = np.array([1, 2])
w = np.array([2, 3])

# Tính inner product giữa v và w
print('method 1 \n', v.dot(w))
print('method 2 \n', np.dot(v, w))

method 1 
 8
method 2 
 8


In [8]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],[4,3]])
v = np.array([1,2])

print('\n matrix X \n', X)
print('\n vector v \n', v)

# phép nhân giữa ma trận và vector
print('\n method 1: X.dot(v) \n', X.dot(v))
print('\n method 1: v.dot(X) \n', v.dot(X))
print('\n method 2: X.dot(v) \n', np.dot(X, v))
print('\n method 2: v.dot(X) \n', np.dot(v, X))


 matrix X 
 [[1 2]
 [4 3]]

 vector v 
 [1 2]

 method 1: X.dot(v) 
 [ 5 10]

 method 1: v.dot(X) 
 [9 8]

 method 2: X.dot(v) 
 [ 5 10]

 method 2: v.dot(X) 
 [9 8]


In [9]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],[4,3]])
Y = np.array([[2,3],[2,1]])

print(' matrix X \n', X)
print('\n matrix Y \n', Y)

# Phép nhân giữa hai ma trận
print('\n method 1 \n', X.dot(Y))
print('\n method 2 \n', np.dot(X, Y))

 matrix X 
 [[1 2]
 [4 3]]

 matrix Y 
 [[2 3]
 [2 1]]

 method 1 
 [[ 6  5]
 [14 15]]

 method 2 
 [[ 6  5]
 [14 15]]


### sum

In [10]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],
              [3,4]])

# Tổng các phần tử của mảng
print(np.sum(X))

 # Tính tổng theo từng cột
print(np.sum(X, axis=0))

# Tính tổng theo từng dòng
print(np.sum(X, axis=1))

10
[4 6]
[3 7]


In [11]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],
              [3,4]])
print(X)

#chuyển vị
print(X.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### argmin and argmax

In [12]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.argmin(x)
print(result)

2


In [13]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.argmax(x)
print(result)

1


### min and max

In [14]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.min(x)
print(result)

1


In [15]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.max(x)
print(result)

7


### sum and average

In [16]:
import numpy as np

x = np.array([6, 5, 7, 1, 9, 2])
result = np.sum(x)
print(result)

30


In [17]:
import numpy as np

x = np.array([6, 5, 7, 1, 9, 2])
result = np.mean(x)
print(result)

5.0
