In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('iris_2D.csv')
data

Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0

In [3]:
labels = data['Label'].to_numpy()
print(labels)
print(labels.shape)

[0. 0. 0. 1. 1. 1.]
(6,)


In [4]:
# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


In [8]:
x_test = np.array([3.5, 1.5]).reshape(1,2)
print(x_test)

[[3.5 1.5]]


In [6]:
distances = np.abs(x_data - x_test).sum(axis=1)
print(distances)

argmin = np.argmin(distances)
print(argmin, labels[argmin])

[3.4 3.3 3.3 1.  1.3 0.3]
5 1.0
