### Simple example

In [2]:
import numpy as np

height, width = 3, 2
img = np.arange(6).reshape(3, 2)
print(img)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
transform = np.array([[1, 0],
                      [0, -1]])
print(transform)

[[ 1  0]
 [ 0 -1]]


In [4]:
A = np.array([[1, 0],
              [0, -1]])

v1 = np.array([1, 0])
print(A.dot(v1))

v2 = np.array([1, 1])
print(A.dot(v2))

v3 = np.array([1, 2])
print(A.dot(v3))

[1 0]
[ 1 -1]
[ 1 -2]


In [5]:
A = np.array([[1, 0],
              [0, -1]])

H = 3
p = np.array([0, H-1])

v1 = np.array([1, 0])
print(A.dot(v1) + p)

v2 = np.array([1, 1])
print(A.dot(v2) + p)

v3 = np.array([1, 2])
print(A.dot(v3) + p)

[1 2]
[1 1]
[1 0]


In [6]:
# implement naively for the sake of simplicity
height = 3
width = 2
img = np.arange(6).reshape(3, 2)

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, H-1])

for x2 in range(height):
    for x1 in range(width):      
        v = np.array([x1, x2])
        new_x1, new_x2 = A.dot(v) + p
        print(f'({x1, x2}) -> ({new_x1}, {new_x2})')
    print()

((0, 0)) -> (0, 2)
((1, 0)) -> (1, 2)

((0, 1)) -> (0, 1)
((1, 1)) -> (1, 1)

((0, 2)) -> (0, 0)
((1, 2)) -> (1, 0)



In [7]:
output = np.zeros((height, width))
print(output)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
# implement naively for the sake of simplicity
height = 3
width = 2
img = np.arange(6).reshape(3, 2)

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, H-1])

for x2 in range(height):
    for x1 in range(width):      
        v = np.array([x1, x2])
        color = img[x2, x1]

        new_x1, new_x2 = A.dot(v) + p
        output[new_x2, new_x1] = color

# print output
print(output)

[[4. 5.]
 [2. 3.]
 [0. 1.]]


### For grayscale images

In [9]:
import cv2
import numpy as np

img = cv2.imread('nature_gray.png', 0)
height, width = img.shape

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height-1])

output = np.zeros((height, width))
for x2 in range(height):
    for x1 in range(width):
        color = img[x2, x1]
        v = np.array([x1, x2])

        new_x1, new_x2 = A.dot(v) + p
        output[new_x2, new_x1] = color

cv2.imwrite('nature_gray_x.png', output)

True

### Improved version of implementation

In [10]:
import numpy as np

height = 3
width = 2
img = np.arange(6).reshape(3, 2)

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height-1])

output = np.zeros((height, width))
for x2 in range(height):
    for x1 in range(width):      
        v = np.array([x1, x2])
        color = img[x2, x1]

        new_x1, new_x2 = A.dot(v) + p
        output[new_x2, new_x1] = color

# print output
print(output)

[[4. 5.]
 [2. 3.]
 [0. 1.]]


In [11]:
A = np.array([[1, 0],
              [0, -1]])

vectors = np.array([[1, 1, 1],
                    [0, 1, 2]])
print(A.dot(vectors))

H = 3
p = np.array([0, H-1]).reshape(2, 1)
print(A.dot(vectors) + p)

[[ 1  1  1]
 [ 0 -1 -2]]
[[1 1 1]
 [2 1 0]]


In [12]:
import numpy as np

height = 3
width = 2
img = np.arange(6).reshape(3, 2)

A = np.array([[1, 0],
              [0, -1]])
p = np.array([0, height-1])

# Create a grid of coordinates
coords = np.indices((height, width)).reshape(2, -1)
coords = np.vstack((coords[1], coords[0])) 

# Apply the transformation
new_coords = A.dot(coords) + np.array([[0], [height-1]])
new_coords = new_coords.reshape(2, height, width)
output = img[new_coords[1], new_coords[0]]
print(output)


[[4 5]
 [2 3]
 [0 1]]


In [13]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature_gray.png', 0)
height, width = img.shape

# Create the transformation matrix
transform = np.array([[1, 0],
                      [0, -1]])

# Create a grid of coordinates
coords = np.indices((height, width)).reshape(2, -1)
coords = np.vstack((coords[1], coords[0]))

# Apply the transformation
new_coords = transform.dot(coords) + np.array([[0], [height-1]])
new_coords = new_coords.reshape(2, height, width)

# Use advanced indexing to apply the transformation
output = img[new_coords[1], new_coords[0]]
cv2.imwrite('nature_gray_x_2.jpg', output)

True