In [2]:
import numpy as np

In [3]:
def create_polynomial_features(X, degree=2): 
    """ Creates the polynomial features
    Args:
        X: A array tensor for the data. 
        degree: A intege for the degree of 
        the generated polynomial function.
    """
    X_new = X
    for i in range(2, degree+1):
        X_new = np.c_[X_new, np.power(X, i)]
    return X_new

X = np.array([[1], [2], [3]])

In [27]:
"""Examples
Input:
X = np.array([[1, 2],
[2, 3], [3, 4]])
degree = 2

Output:
X_poly = np.array([[1, 1, 2, 4],[2, 4, 3, 9], [3, 9, 4, 16]])"""

def create_polynomial_features_2(X, degree=2):
    """ Creates the polynomial features
    Args:
        X: A array tensor for the data. 
        degree: A intege for the degree of 
        the generated polynomial function.
    """

    X_mem = []
    for X_sub in X.T:
        print(X_sub)
        X_sub = X_sub.T
        X_new = X_sub
        for i in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, i)]
            print(X_new)
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [28]:
X = np.array([[1, 2], [2, 3], [3, 4]])
print(create_polynomial_features_2(X, 2))

[1 2 3]
[[1 1]
 [2 4]
 [3 9]]
[2 3 4]
[[ 2  4]
 [ 3  9]
 [ 4 16]]
[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]
