In [2]:
# Vector length
import numpy as np


def compute_vector_length(vector):
    len_of_vector = np.sqrt(np.sum(np.square(vector)))
    return len_of_vector


print(compute_vector_length([1, 2, 3, 4, 5]))

7.416198487095663


In [3]:
# Dot product
def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result


print(compute_dot_product([1, 2, 3, 4, 5], [5, 4, 3, 2, 1]))

35


In [4]:
# Matrix multi vector
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result


print(matrix_multi_vector([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2, 3]))

[14 32 50]


In [5]:
# Matrix multi matrix

def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result


print(matrix_multi_matrix([[1, 2, 3], [4, 5, 6], [
      7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [7]:
# Matrix inverse

def inverse_matrix(matrix):
    det = np.linalg.det(matrix)
    if det == 0:
        return None
    else:
        result = np.linalg.inv(matrix)
        return result


print(inverse_matrix([[-2, 8], [6, -4]]))

[[0.1  0.2 ]
 [0.15 0.05]]


In [8]:
# Eigenvector and Eigenvalues

def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues = np.linalg.eig(matrix)[0]
    eigenvectors = np.linalg.eig(matrix)[1]

    return eigenvalues, eigenvectors


print(compute_eigenvalues_eigenvectors([[0.9, 0.1], [0.2, 0.8]]))

(array([1. , 0.7]), array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]]))


In [9]:
# Cosine similarity
def compute_cosine(v1, v2):
    dot_product = np.dot(v1, v2)
    len_v1 = np.sqrt(np.sum(np.square(v1)))
    len_v2 = np.sqrt(np.sum(np.square(v2)))
    cos_sim = dot_product / (len_v1 * len_v2)
    return cos_sim


print(compute_cosine([1, 2, 3, 4], [1, 0, 3, 0]))

0.5773502691896257
